# Generated by Django 2.1.7 on 2019-06-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='emision_date',
            new_name='notification',
        ),
    ]
