# Generated by Django 2.1.7 on 2019-06-01 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alarm', '0002_auto_20190601_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carenetwork',
            name='careman',
        ),
        migrations.AddField(
            model_name='carenetwork',
            name='careman',
            field=models.ManyToManyField(blank=True, related_name='careman_assigned', to='alarm.Careman'),
        ),
    ]
