# Generated by Django 2.1.7 on 2019-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20190601_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenetwork',
            name='careman',
            field=models.ManyToManyField(to='alarm.Careman'),
        ),
    ]
