# Generated by Django 2.1.7 on 2019-06-01 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_auto_20190601_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careman',
            name='name',
        ),
        migrations.AlterField(
            model_name='carenetwork',
            name='careman',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Careman',
        ),
    ]
